name: GitHub Snake animation

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: platane/github-contribution-grid-snake-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: snake.svg

      - name: Commit Snake
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add snake.svg
          git commit -m "Update snake contribution graph"
          git push
